// <auto-generated />
using G02_07_EF_CF_OTM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G02_07_EF_CF_OTM.Migrations
{
    [DbContext(typeof(LibrerieContext))]
    [Migration("20250214143115_Iniziale")]
    partial class Iniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G02_07_EF_CF_OTM.Models.Autore", b =>
                {
                    b.Property<int>("AutoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoreID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutoreID");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("G02_07_EF_CF_OTM.Models.Libro", b =>
                {
                    b.Property<int>("LibroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroID"));

                    b.Property<int>("AutoreRIF")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroID");

                    b.HasIndex("AutoreRIF");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("G02_07_EF_CF_OTM.Models.Libro", b =>
                {
                    b.HasOne("G02_07_EF_CF_OTM.Models.Autore", "AutoreNav")
                        .WithMany("Libri")
                        .HasForeignKey("AutoreRIF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoreNav");
                });

            modelBuilder.Entity("G02_07_EF_CF_OTM.Models.Autore", b =>
                {
                    b.Navigation("Libri");
                });
#pragma warning restore 612, 618
        }
    }
}
